import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import { colors } from "@/styles/theme";

const urbanist = Urbanist({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-urbanist",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cssVars: React.CSSProperties & { [key: string]: string } = {
    "--brand": colors.brand,
    "--ink": colors.ink,
    "--background": colors.background,
    "--foreground": colors.foreground,
  // neutral tokens for dark mode surfaces
  "--neutral-bg-dark": colors.neutralBgDark,
  "--neutral-card-dark": colors.neutralCardDark,
  "--neutral-border-dark": colors.neutralBorderDark,
  "--neutral-input-dark": colors.neutralInputDark,
  "--neutral-placeholder-dark": colors.neutralPlaceholderDark,
  };
  return (
    <html lang="en" style={cssVars}>
      <body
        className={`${urbanist.variable} font-urbanist antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
